on:
  push:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test*'
  pull_request:
    paths:
      - '**.sublime-syntax'
      - '**/syntax_test*'

jobs:
  syntax_tests:
    name: Syntax Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
